// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: db_service.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message definitions for Users
type User struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email               string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Username            string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash        string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	IsActive            bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	IsEmailVerified     bool                   `protobuf:"varint,6,opt,name=is_email_verified,json=isEmailVerified,proto3" json:"is_email_verified,omitempty"`
	Role                string                 `protobuf:"bytes,7,opt,name=role,proto3" json:"role,omitempty"`
	StorageQuota        int64                  `protobuf:"varint,8,opt,name=storage_quota,json=storageQuota,proto3" json:"storage_quota,omitempty"`
	UsedSpace           int64                  `protobuf:"varint,9,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	CreatedAt           *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt           *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	FailedLoginAttempts int32                  `protobuf:"varint,12,opt,name=failed_login_attempts,json=failedLoginAttempts,proto3" json:"failed_login_attempts,omitempty"`
	LockedUntil         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=locked_until,json=lockedUntil,proto3" json:"locked_until,omitempty"`
	LastLogin           *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_db_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetIsEmailVerified() bool {
	if x != nil {
		return x.IsEmailVerified
	}
	return false
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetStorageQuota() int64 {
	if x != nil {
		return x.StorageQuota
	}
	return 0
}

func (x *User) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *User) GetFailedLoginAttempts() int32 {
	if x != nil {
		return x.FailedLoginAttempts
	}
	return 0
}

func (x *User) GetLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedUntil
	}
	return nil
}

func (x *User) GetLastLogin() *timestamppb.Timestamp {
	if x != nil {
		return x.LastLogin
	}
	return nil
}

type UserID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserID) Reset() {
	*x = UserID{}
	mi := &file_db_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserID) ProtoMessage() {}

func (x *UserID) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserID.ProtoReflect.Descriptor instead.
func (*UserID) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{1}
}

func (x *UserID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type EmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailRequest) Reset() {
	*x = EmailRequest{}
	mi := &file_db_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailRequest) ProtoMessage() {}

func (x *EmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailRequest.ProtoReflect.Descriptor instead.
func (*EmailRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{2}
}

func (x *EmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type UsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsernameRequest) Reset() {
	*x = UsernameRequest{}
	mi := &file_db_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameRequest) ProtoMessage() {}

func (x *UsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameRequest.ProtoReflect.Descriptor instead.
func (*UsernameRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{3}
}

func (x *UsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdatePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePasswordRequest) Reset() {
	*x = UpdatePasswordRequest{}
	mi := &file_db_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePasswordRequest) ProtoMessage() {}

func (x *UpdatePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePasswordRequest.ProtoReflect.Descriptor instead.
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdatePasswordRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdatePasswordRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

type UpdateUsernameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateUsernameRequest) Reset() {
	*x = UpdateUsernameRequest{}
	mi := &file_db_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateUsernameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUsernameRequest) ProtoMessage() {}

func (x *UpdateUsernameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUsernameRequest.ProtoReflect.Descriptor instead.
func (*UpdateUsernameRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateUsernameRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateUsernameRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type UpdateEmailVerificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	IsVerified    bool                   `protobuf:"varint,2,opt,name=is_verified,json=isVerified,proto3" json:"is_verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEmailVerificationRequest) Reset() {
	*x = UpdateEmailVerificationRequest{}
	mi := &file_db_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEmailVerificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEmailVerificationRequest) ProtoMessage() {}

func (x *UpdateEmailVerificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEmailVerificationRequest.ProtoReflect.Descriptor instead.
func (*UpdateEmailVerificationRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEmailVerificationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEmailVerificationRequest) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

type UpdateFailedLoginAttemptsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Attempts      int32                  `protobuf:"varint,2,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFailedLoginAttemptsRequest) Reset() {
	*x = UpdateFailedLoginAttemptsRequest{}
	mi := &file_db_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFailedLoginAttemptsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFailedLoginAttemptsRequest) ProtoMessage() {}

func (x *UpdateFailedLoginAttemptsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFailedLoginAttemptsRequest.ProtoReflect.Descriptor instead.
func (*UpdateFailedLoginAttemptsRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateFailedLoginAttemptsRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFailedLoginAttemptsRequest) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type UpdateLockedUntilRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	LockedUntil   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=locked_until,json=lockedUntil,proto3" json:"locked_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLockedUntilRequest) Reset() {
	*x = UpdateLockedUntilRequest{}
	mi := &file_db_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLockedUntilRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLockedUntilRequest) ProtoMessage() {}

func (x *UpdateLockedUntilRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLockedUntilRequest.ProtoReflect.Descriptor instead.
func (*UpdateLockedUntilRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLockedUntilRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLockedUntilRequest) GetLockedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedUntil
	}
	return nil
}

type UpdateStorageUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UsedSpace     int64                  `protobuf:"varint,2,opt,name=used_space,json=usedSpace,proto3" json:"used_space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStorageUsageRequest) Reset() {
	*x = UpdateStorageUsageRequest{}
	mi := &file_db_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStorageUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStorageUsageRequest) ProtoMessage() {}

func (x *UpdateStorageUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStorageUsageRequest.ProtoReflect.Descriptor instead.
func (*UpdateStorageUsageRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateStorageUsageRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStorageUsageRequest) GetUsedSpace() int64 {
	if x != nil {
		return x.UsedSpace
	}
	return 0
}

type ExistsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exists        bool                   `protobuf:"varint,1,opt,name=exists,proto3" json:"exists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExistsResponse) Reset() {
	*x = ExistsResponse{}
	mi := &file_db_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExistsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExistsResponse) ProtoMessage() {}

func (x *ExistsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExistsResponse.ProtoReflect.Descriptor instead.
func (*ExistsResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{10}
}

func (x *ExistsResponse) GetExists() bool {
	if x != nil {
		return x.Exists
	}
	return false
}

// Message definitions for Files
type File struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnerId        string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ParentId       string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	FileExtension  string                 `protobuf:"bytes,5,opt,name=file_extension,json=fileExtension,proto3" json:"file_extension,omitempty"`
	MimeType       string                 `protobuf:"bytes,6,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	StoragePath    string                 `protobuf:"bytes,7,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	Size           int64                  `protobuf:"varint,8,opt,name=size,proto3" json:"size,omitempty"`
	Md5Checksum    string                 `protobuf:"bytes,9,opt,name=md5_checksum,json=md5Checksum,proto3" json:"md5_checksum,omitempty"`
	Sha256Checksum string                 `protobuf:"bytes,10,opt,name=sha256_checksum,json=sha256Checksum,proto3" json:"sha256_checksum,omitempty"`
	IsFolder       bool                   `protobuf:"varint,11,opt,name=is_folder,json=isFolder,proto3" json:"is_folder,omitempty"`
	IsTrashed      bool                   `protobuf:"varint,12,opt,name=is_trashed,json=isTrashed,proto3" json:"is_trashed,omitempty"`
	TrashedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=trashed_at,json=trashedAt,proto3" json:"trashed_at,omitempty"`
	Starred        bool                   `protobuf:"varint,14,opt,name=starred,proto3" json:"starred,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastViewedAt   *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=last_viewed_at,json=lastViewedAt,proto3" json:"last_viewed_at,omitempty"`
	ViewedByMe     bool                   `protobuf:"varint,18,opt,name=viewed_by_me,json=viewedByMe,proto3" json:"viewed_by_me,omitempty"`
	Version        int64                  `protobuf:"varint,19,opt,name=version,proto3" json:"version,omitempty"`
	RevisionId     string                 `protobuf:"bytes,20,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	IndexableText  string                 `protobuf:"bytes,21,opt,name=indexable_text,json=indexableText,proto3" json:"indexable_text,omitempty"`
	ThumbnailLink  string                 `protobuf:"bytes,22,opt,name=thumbnail_link,json=thumbnailLink,proto3" json:"thumbnail_link,omitempty"`
	WebViewLink    string                 `protobuf:"bytes,23,opt,name=web_view_link,json=webViewLink,proto3" json:"web_view_link,omitempty"`
	WebContentLink string                 `protobuf:"bytes,24,opt,name=web_content_link,json=webContentLink,proto3" json:"web_content_link,omitempty"`
	IconLink       string                 `protobuf:"bytes,25,opt,name=icon_link,json=iconLink,proto3" json:"icon_link,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_db_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{11}
}

func (x *File) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *File) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *File) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetFileExtension() string {
	if x != nil {
		return x.FileExtension
	}
	return ""
}

func (x *File) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *File) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *File) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *File) GetMd5Checksum() string {
	if x != nil {
		return x.Md5Checksum
	}
	return ""
}

func (x *File) GetSha256Checksum() string {
	if x != nil {
		return x.Sha256Checksum
	}
	return ""
}

func (x *File) GetIsFolder() bool {
	if x != nil {
		return x.IsFolder
	}
	return false
}

func (x *File) GetIsTrashed() bool {
	if x != nil {
		return x.IsTrashed
	}
	return false
}

func (x *File) GetTrashedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.TrashedAt
	}
	return nil
}

func (x *File) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

func (x *File) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *File) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *File) GetLastViewedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastViewedAt
	}
	return nil
}

func (x *File) GetViewedByMe() bool {
	if x != nil {
		return x.ViewedByMe
	}
	return false
}

func (x *File) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *File) GetRevisionId() string {
	if x != nil {
		return x.RevisionId
	}
	return ""
}

func (x *File) GetIndexableText() string {
	if x != nil {
		return x.IndexableText
	}
	return ""
}

func (x *File) GetThumbnailLink() string {
	if x != nil {
		return x.ThumbnailLink
	}
	return ""
}

func (x *File) GetWebViewLink() string {
	if x != nil {
		return x.WebViewLink
	}
	return ""
}

func (x *File) GetWebContentLink() string {
	if x != nil {
		return x.WebContentLink
	}
	return ""
}

func (x *File) GetIconLink() string {
	if x != nil {
		return x.IconLink
	}
	return ""
}

type FileID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileID) Reset() {
	*x = FileID{}
	mi := &file_db_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileID) ProtoMessage() {}

func (x *FileID) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileID.ProtoReflect.Descriptor instead.
func (*FileID) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{12}
}

func (x *FileID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetFileByPathRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileByPathRequest) Reset() {
	*x = GetFileByPathRequest{}
	mi := &file_db_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileByPathRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileByPathRequest) ProtoMessage() {}

func (x *GetFileByPathRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileByPathRequest.ProtoReflect.Descriptor instead.
func (*GetFileByPathRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetFileByPathRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetFileByPathRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	IsTrashed     bool                   `protobuf:"varint,3,opt,name=is_trashed,json=isTrashed,proto3" json:"is_trashed,omitempty"`
	Starred       bool                   `protobuf:"varint,4,opt,name=starred,proto3" json:"starred,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	OrderBy       string                 `protobuf:"bytes,7,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	OrderDir      string                 `protobuf:"bytes,8,opt,name=order_dir,json=orderDir,proto3" json:"order_dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesRequest) Reset() {
	*x = ListFilesRequest{}
	mi := &file_db_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesRequest) ProtoMessage() {}

func (x *ListFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesRequest.ProtoReflect.Descriptor instead.
func (*ListFilesRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{14}
}

func (x *ListFilesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListFilesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListFilesRequest) GetIsTrashed() bool {
	if x != nil {
		return x.IsTrashed
	}
	return false
}

func (x *ListFilesRequest) GetStarred() bool {
	if x != nil {
		return x.Starred
	}
	return false
}

func (x *ListFilesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFilesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListFilesRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListFilesRequest) GetOrderDir() string {
	if x != nil {
		return x.OrderDir
	}
	return ""
}

type ListFilesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*File                `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesResponse) Reset() {
	*x = ListFilesResponse{}
	mi := &file_db_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesResponse) ProtoMessage() {}

func (x *ListFilesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesResponse.ProtoReflect.Descriptor instead.
func (*ListFilesResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{15}
}

func (x *ListFilesResponse) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListFilesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListFilesResponse) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListFilesResponse) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListFilesByParentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	ParentId      string                 `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFilesByParentRequest) Reset() {
	*x = ListFilesByParentRequest{}
	mi := &file_db_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFilesByParentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFilesByParentRequest) ProtoMessage() {}

func (x *ListFilesByParentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFilesByParentRequest.ProtoReflect.Descriptor instead.
func (*ListFilesByParentRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{16}
}

func (x *ListFilesByParentRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *ListFilesByParentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

type ListStarredFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStarredFilesRequest) Reset() {
	*x = ListStarredFilesRequest{}
	mi := &file_db_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStarredFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStarredFilesRequest) ProtoMessage() {}

func (x *ListStarredFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStarredFilesRequest.ProtoReflect.Descriptor instead.
func (*ListStarredFilesRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{17}
}

func (x *ListStarredFilesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type ListTrashedFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTrashedFilesRequest) Reset() {
	*x = ListTrashedFilesRequest{}
	mi := &file_db_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTrashedFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTrashedFilesRequest) ProtoMessage() {}

func (x *ListTrashedFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTrashedFilesRequest.ProtoReflect.Descriptor instead.
func (*ListTrashedFilesRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{18}
}

func (x *ListTrashedFilesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type SearchFilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchFilesRequest) Reset() {
	*x = SearchFilesRequest{}
	mi := &file_db_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchFilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchFilesRequest) ProtoMessage() {}

func (x *SearchFilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchFilesRequest.ProtoReflect.Descriptor instead.
func (*SearchFilesRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{19}
}

func (x *SearchFilesRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *SearchFilesRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type FileSizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Size          int64                  `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileSizeResponse) Reset() {
	*x = FileSizeResponse{}
	mi := &file_db_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileSizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileSizeResponse) ProtoMessage() {}

func (x *FileSizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileSizeResponse.ProtoReflect.Descriptor instead.
func (*FileSizeResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{20}
}

func (x *FileSizeResponse) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type UpdateFileSizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileSizeRequest) Reset() {
	*x = UpdateFileSizeRequest{}
	mi := &file_db_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileSizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileSizeRequest) ProtoMessage() {}

func (x *UpdateFileSizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileSizeRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileSizeRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{21}
}

func (x *UpdateFileSizeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateFileSizeRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetFileTreeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OwnerId       string                 `protobuf:"bytes,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	RootId        string                 `protobuf:"bytes,2,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFileTreeRequest) Reset() {
	*x = GetFileTreeRequest{}
	mi := &file_db_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFileTreeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFileTreeRequest) ProtoMessage() {}

func (x *GetFileTreeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFileTreeRequest.ProtoReflect.Descriptor instead.
func (*GetFileTreeRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{22}
}

func (x *GetFileTreeRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *GetFileTreeRequest) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

// Message definitions for File Revisions
type FileRevision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	RevisionId    int64                  `protobuf:"varint,3,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	Md5Checksum   string                 `protobuf:"bytes,4,opt,name=md5_checksum,json=md5Checksum,proto3" json:"md5_checksum,omitempty"`
	Size          int64                  `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StoragePath   string                 `protobuf:"bytes,7,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	MimeType      string                 `protobuf:"bytes,8,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	UserId        string                 `protobuf:"bytes,9,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRevision) Reset() {
	*x = FileRevision{}
	mi := &file_db_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRevision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRevision) ProtoMessage() {}

func (x *FileRevision) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRevision.ProtoReflect.Descriptor instead.
func (*FileRevision) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{23}
}

func (x *FileRevision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FileRevision) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FileRevision) GetRevisionId() int64 {
	if x != nil {
		return x.RevisionId
	}
	return 0
}

func (x *FileRevision) GetMd5Checksum() string {
	if x != nil {
		return x.Md5Checksum
	}
	return ""
}

func (x *FileRevision) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileRevision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FileRevision) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *FileRevision) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *FileRevision) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type RevisionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevisionID) Reset() {
	*x = RevisionID{}
	mi := &file_db_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevisionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevisionID) ProtoMessage() {}

func (x *RevisionID) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevisionID.ProtoReflect.Descriptor instead.
func (*RevisionID) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{24}
}

func (x *RevisionID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListRevisionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revisions     []*FileRevision        `protobuf:"bytes,1,rep,name=revisions,proto3" json:"revisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRevisionsResponse) Reset() {
	*x = ListRevisionsResponse{}
	mi := &file_db_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRevisionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRevisionsResponse) ProtoMessage() {}

func (x *ListRevisionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRevisionsResponse.ProtoReflect.Descriptor instead.
func (*ListRevisionsResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{25}
}

func (x *ListRevisionsResponse) GetRevisions() []*FileRevision {
	if x != nil {
		return x.Revisions
	}
	return nil
}

type GetRevisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	RevisionId    int64                  `protobuf:"varint,2,opt,name=revision_id,json=revisionId,proto3" json:"revision_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRevisionRequest) Reset() {
	*x = GetRevisionRequest{}
	mi := &file_db_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRevisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRevisionRequest) ProtoMessage() {}

func (x *GetRevisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRevisionRequest.ProtoReflect.Descriptor instead.
func (*GetRevisionRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{26}
}

func (x *GetRevisionRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetRevisionRequest) GetRevisionId() int64 {
	if x != nil {
		return x.RevisionId
	}
	return 0
}

// Message definitions for File Permissions
type FilePermission struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileId        string                 `protobuf:"bytes,2,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	GranteeId     string                 `protobuf:"bytes,3,opt,name=grantee_id,json=granteeId,proto3" json:"grantee_id,omitempty"`
	GranteeType   string                 `protobuf:"bytes,4,opt,name=grantee_type,json=granteeType,proto3" json:"grantee_type,omitempty"`
	Role          string                 `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	AllowShare    bool                   `protobuf:"varint,6,opt,name=allow_share,json=allowShare,proto3" json:"allow_share,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilePermission) Reset() {
	*x = FilePermission{}
	mi := &file_db_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilePermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilePermission) ProtoMessage() {}

func (x *FilePermission) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilePermission.ProtoReflect.Descriptor instead.
func (*FilePermission) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{27}
}

func (x *FilePermission) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FilePermission) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *FilePermission) GetGranteeId() string {
	if x != nil {
		return x.GranteeId
	}
	return ""
}

func (x *FilePermission) GetGranteeType() string {
	if x != nil {
		return x.GranteeType
	}
	return ""
}

func (x *FilePermission) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *FilePermission) GetAllowShare() bool {
	if x != nil {
		return x.AllowShare
	}
	return false
}

func (x *FilePermission) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PermissionID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionID) Reset() {
	*x = PermissionID{}
	mi := &file_db_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionID) ProtoMessage() {}

func (x *PermissionID) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionID.ProtoReflect.Descriptor instead.
func (*PermissionID) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{28}
}

func (x *PermissionID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListPermissionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Permissions   []*FilePermission      `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPermissionsResponse) Reset() {
	*x = ListPermissionsResponse{}
	mi := &file_db_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPermissionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPermissionsResponse) ProtoMessage() {}

func (x *ListPermissionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPermissionsResponse.ProtoReflect.Descriptor instead.
func (*ListPermissionsResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{29}
}

func (x *ListPermissionsResponse) GetPermissions() []*FilePermission {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type CheckPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequiredRole  string                 `protobuf:"bytes,3,opt,name=required_role,json=requiredRole,proto3" json:"required_role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_db_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{30}
}

func (x *CheckPermissionRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CheckPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckPermissionRequest) GetRequiredRole() string {
	if x != nil {
		return x.RequiredRole
	}
	return ""
}

type PermissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasPermission bool                   `protobuf:"varint,1,opt,name=has_permission,json=hasPermission,proto3" json:"has_permission,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PermissionResponse) Reset() {
	*x = PermissionResponse{}
	mi := &file_db_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PermissionResponse) ProtoMessage() {}

func (x *PermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PermissionResponse.ProtoReflect.Descriptor instead.
func (*PermissionResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{31}
}

func (x *PermissionResponse) GetHasPermission() bool {
	if x != nil {
		return x.HasPermission
	}
	return false
}

// File metadata operations
type UpdateFileMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFileMetadataRequest) Reset() {
	*x = UpdateFileMetadataRequest{}
	mi := &file_db_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFileMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFileMetadataRequest) ProtoMessage() {}

func (x *UpdateFileMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFileMetadataRequest.ProtoReflect.Descriptor instead.
func (*UpdateFileMetadataRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateFileMetadataRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UpdateFileMetadataRequest) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type FileMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      string                 `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMetadataResponse) Reset() {
	*x = FileMetadataResponse{}
	mi := &file_db_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMetadataResponse) ProtoMessage() {}

func (x *FileMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMetadataResponse.ProtoReflect.Descriptor instead.
func (*FileMetadataResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{33}
}

func (x *FileMetadataResponse) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

// File operations (star, move, copy, rename)
type MoveFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	NewParentId   string                 `protobuf:"bytes,2,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveFileRequest) Reset() {
	*x = MoveFileRequest{}
	mi := &file_db_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveFileRequest) ProtoMessage() {}

func (x *MoveFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveFileRequest.ProtoReflect.Descriptor instead.
func (*MoveFileRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{34}
}

func (x *MoveFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *MoveFileRequest) GetNewParentId() string {
	if x != nil {
		return x.NewParentId
	}
	return ""
}

type CopyFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	NewParentId   string                 `protobuf:"bytes,2,opt,name=new_parent_id,json=newParentId,proto3" json:"new_parent_id,omitempty"`
	NewName       string                 `protobuf:"bytes,3,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CopyFileRequest) Reset() {
	*x = CopyFileRequest{}
	mi := &file_db_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyFileRequest) ProtoMessage() {}

func (x *CopyFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyFileRequest.ProtoReflect.Descriptor instead.
func (*CopyFileRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{35}
}

func (x *CopyFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *CopyFileRequest) GetNewParentId() string {
	if x != nil {
		return x.NewParentId
	}
	return ""
}

func (x *CopyFileRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

type RenameFileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	NewName       string                 `protobuf:"bytes,2,opt,name=new_name,json=newName,proto3" json:"new_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameFileRequest) Reset() {
	*x = RenameFileRequest{}
	mi := &file_db_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameFileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameFileRequest) ProtoMessage() {}

func (x *RenameFileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameFileRequest.ProtoReflect.Descriptor instead.
func (*RenameFileRequest) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{36}
}

func (x *RenameFileRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *RenameFileRequest) GetNewName() string {
	if x != nil {
		return x.NewName
	}
	return ""
}

// File integrity operations
type IntegrityResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	IsIntegrityVerified bool                   `protobuf:"varint,1,opt,name=is_integrity_verified,json=isIntegrityVerified,proto3" json:"is_integrity_verified,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *IntegrityResponse) Reset() {
	*x = IntegrityResponse{}
	mi := &file_db_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrityResponse) ProtoMessage() {}

func (x *IntegrityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrityResponse.ProtoReflect.Descriptor instead.
func (*IntegrityResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{37}
}

func (x *IntegrityResponse) GetIsIntegrityVerified() bool {
	if x != nil {
		return x.IsIntegrityVerified
	}
	return false
}

type ChecksumsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checksums     map[string]string      `protobuf:"bytes,1,rep,name=checksums,proto3" json:"checksums,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksumsResponse) Reset() {
	*x = ChecksumsResponse{}
	mi := &file_db_service_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksumsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksumsResponse) ProtoMessage() {}

func (x *ChecksumsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_db_service_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksumsResponse.ProtoReflect.Descriptor instead.
func (*ChecksumsResponse) Descriptor() ([]byte, []int) {
	return file_db_service_proto_rawDescGZIP(), []int{38}
}

func (x *ChecksumsResponse) GetChecksums() map[string]string {
	if x != nil {
		return x.Checksums
	}
	return nil
}

var File_db_service_proto protoreflect.FileDescriptor

const file_db_service_proto_rawDesc = "" +
	"\n" +
	"\x10db_service.proto\x12\tdbservice\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xb2\x04\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\x12*\n" +
	"\x11is_email_verified\x18\x06 \x01(\bR\x0fisEmailVerified\x12\x12\n" +
	"\x04role\x18\a \x01(\tR\x04role\x12#\n" +
	"\rstorage_quota\x18\b \x01(\x03R\fstorageQuota\x12\x1d\n" +
	"\n" +
	"used_space\x18\t \x01(\x03R\tusedSpace\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x122\n" +
	"\x15failed_login_attempts\x18\f \x01(\x05R\x13failedLoginAttempts\x12=\n" +
	"\flocked_until\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vlockedUntil\x129\n" +
	"\n" +
	"last_login\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tlastLogin\"\x18\n" +
	"\x06UserID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\fEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"-\n" +
	"\x0fUsernameRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"L\n" +
	"\x15UpdatePasswordRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\"C\n" +
	"\x15UpdateUsernameRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"Q\n" +
	"\x1eUpdateEmailVerificationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vis_verified\x18\x02 \x01(\bR\n" +
	"isVerified\"N\n" +
	" UpdateFailedLoginAttemptsRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\battempts\x18\x02 \x01(\x05R\battempts\"i\n" +
	"\x18UpdateLockedUntilRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\flocked_until\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vlockedUntil\"J\n" +
	"\x19UpdateStorageUsageRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"used_space\x18\x02 \x01(\x03R\tusedSpace\"(\n" +
	"\x0eExistsResponse\x12\x16\n" +
	"\x06exists\x18\x01 \x01(\bR\x06exists\"\x88\a\n" +
	"\x04File\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12%\n" +
	"\x0efile_extension\x18\x05 \x01(\tR\rfileExtension\x12\x1b\n" +
	"\tmime_type\x18\x06 \x01(\tR\bmimeType\x12!\n" +
	"\fstorage_path\x18\a \x01(\tR\vstoragePath\x12\x12\n" +
	"\x04size\x18\b \x01(\x03R\x04size\x12!\n" +
	"\fmd5_checksum\x18\t \x01(\tR\vmd5Checksum\x12'\n" +
	"\x0fsha256_checksum\x18\n" +
	" \x01(\tR\x0esha256Checksum\x12\x1b\n" +
	"\tis_folder\x18\v \x01(\bR\bisFolder\x12\x1d\n" +
	"\n" +
	"is_trashed\x18\f \x01(\bR\tisTrashed\x129\n" +
	"\n" +
	"trashed_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttrashedAt\x12\x18\n" +
	"\astarred\x18\x0e \x01(\bR\astarred\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12@\n" +
	"\x0elast_viewed_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\flastViewedAt\x12 \n" +
	"\fviewed_by_me\x18\x12 \x01(\bR\n" +
	"viewedByMe\x12\x18\n" +
	"\aversion\x18\x13 \x01(\x03R\aversion\x12\x1f\n" +
	"\vrevision_id\x18\x14 \x01(\tR\n" +
	"revisionId\x12%\n" +
	"\x0eindexable_text\x18\x15 \x01(\tR\rindexableText\x12%\n" +
	"\x0ethumbnail_link\x18\x16 \x01(\tR\rthumbnailLink\x12\"\n" +
	"\rweb_view_link\x18\x17 \x01(\tR\vwebViewLink\x12(\n" +
	"\x10web_content_link\x18\x18 \x01(\tR\x0ewebContentLink\x12\x1b\n" +
	"\ticon_link\x18\x19 \x01(\tR\biconLink\"\x18\n" +
	"\x06FileID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"E\n" +
	"\x14GetFileByPathRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xe9\x01\n" +
	"\x10ListFilesRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x19\n" +
	"\bowner_id\x18\x02 \x01(\tR\aownerId\x12\x1d\n" +
	"\n" +
	"is_trashed\x18\x03 \x01(\bR\tisTrashed\x12\x18\n" +
	"\astarred\x18\x04 \x01(\bR\astarred\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\x12\x19\n" +
	"\border_by\x18\a \x01(\tR\aorderBy\x12\x1b\n" +
	"\torder_dir\x18\b \x01(\tR\borderDir\"~\n" +
	"\x11ListFilesResponse\x12%\n" +
	"\x05files\x18\x01 \x03(\v2\x0f.dbservice.FileR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x04 \x01(\x05R\x06offset\"R\n" +
	"\x18ListFilesByParentRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x1b\n" +
	"\tparent_id\x18\x02 \x01(\tR\bparentId\"4\n" +
	"\x17ListStarredFilesRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"4\n" +
	"\x17ListTrashedFilesRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\"E\n" +
	"\x12SearchFilesRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\"&\n" +
	"\x10FileSizeResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x03R\x04size\";\n" +
	"\x15UpdateFileSizeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"H\n" +
	"\x12GetFileTreeRequest\x12\x19\n" +
	"\bowner_id\x18\x01 \x01(\tR\aownerId\x12\x17\n" +
	"\aroot_id\x18\x02 \x01(\tR\x06rootId\"\xa3\x02\n" +
	"\fFileRevision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vrevision_id\x18\x03 \x01(\x03R\n" +
	"revisionId\x12!\n" +
	"\fmd5_checksum\x18\x04 \x01(\tR\vmd5Checksum\x12\x12\n" +
	"\x04size\x18\x05 \x01(\x03R\x04size\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12!\n" +
	"\fstorage_path\x18\a \x01(\tR\vstoragePath\x12\x1b\n" +
	"\tmime_type\x18\b \x01(\tR\bmimeType\x12\x17\n" +
	"\auser_id\x18\t \x01(\tR\x06userId\"\x1c\n" +
	"\n" +
	"RevisionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"N\n" +
	"\x15ListRevisionsResponse\x125\n" +
	"\trevisions\x18\x01 \x03(\v2\x17.dbservice.FileRevisionR\trevisions\"N\n" +
	"\x12GetRevisionRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1f\n" +
	"\vrevision_id\x18\x02 \x01(\x03R\n" +
	"revisionId\"\xeb\x01\n" +
	"\x0eFilePermission\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\afile_id\x18\x02 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"grantee_id\x18\x03 \x01(\tR\tgranteeId\x12!\n" +
	"\fgrantee_type\x18\x04 \x01(\tR\vgranteeType\x12\x12\n" +
	"\x04role\x18\x05 \x01(\tR\x04role\x12\x1f\n" +
	"\vallow_share\x18\x06 \x01(\bR\n" +
	"allowShare\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x1e\n" +
	"\fPermissionID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x17ListPermissionsResponse\x12;\n" +
	"\vpermissions\x18\x01 \x03(\v2\x19.dbservice.FilePermissionR\vpermissions\"o\n" +
	"\x16CheckPermissionRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12#\n" +
	"\rrequired_role\x18\x03 \x01(\tR\frequiredRole\";\n" +
	"\x12PermissionResponse\x12%\n" +
	"\x0ehas_permission\x18\x01 \x01(\bR\rhasPermission\"P\n" +
	"\x19UpdateFileMetadataRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"2\n" +
	"\x14FileMetadataResponse\x12\x1a\n" +
	"\bmetadata\x18\x01 \x01(\tR\bmetadata\"N\n" +
	"\x0fMoveFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\"\n" +
	"\rnew_parent_id\x18\x02 \x01(\tR\vnewParentId\"i\n" +
	"\x0fCopyFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\"\n" +
	"\rnew_parent_id\x18\x02 \x01(\tR\vnewParentId\x12\x19\n" +
	"\bnew_name\x18\x03 \x01(\tR\anewName\"G\n" +
	"\x11RenameFileRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x19\n" +
	"\bnew_name\x18\x02 \x01(\tR\anewName\"G\n" +
	"\x11IntegrityResponse\x122\n" +
	"\x15is_integrity_verified\x18\x01 \x01(\bR\x13isIntegrityVerified\"\x9c\x01\n" +
	"\x11ChecksumsResponse\x12I\n" +
	"\tchecksums\x18\x01 \x03(\v2+.dbservice.ChecksumsResponse.ChecksumsEntryR\tchecksums\x1a<\n" +
	"\x0eChecksumsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xac\x1a\n" +
	"\tDBService\x122\n" +
	"\n" +
	"CreateUser\x12\x0f.dbservice.User\x1a\x11.dbservice.UserID\"\x00\x123\n" +
	"\vGetUserByID\x12\x11.dbservice.UserID\x1a\x0f.dbservice.User\"\x00\x12<\n" +
	"\x0eGetUserByEmail\x12\x17.dbservice.EmailRequest\x1a\x0f.dbservice.User\"\x00\x127\n" +
	"\n" +
	"UpdateUser\x12\x0f.dbservice.User\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x0eUpdatePassword\x12 .dbservice.UpdatePasswordRequest\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\x0eUpdateUsername\x12 .dbservice.UpdateUsernameRequest\x1a\x16.google.protobuf.Empty\"\x00\x12^\n" +
	"\x17UpdateEmailVerification\x12).dbservice.UpdateEmailVerificationRequest\x1a\x16.google.protobuf.Empty\"\x00\x12>\n" +
	"\x0fUpdateLastLogin\x12\x11.dbservice.UserID\x1a\x16.google.protobuf.Empty\"\x00\x12b\n" +
	"\x19UpdateFailedLoginAttempts\x12+.dbservice.UpdateFailedLoginAttemptsRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\x11UpdateLockedUntil\x12#.dbservice.UpdateLockedUntilRequest\x1a\x16.google.protobuf.Empty\"\x00\x12T\n" +
	"\x12UpdateStorageUsage\x12$.dbservice.UpdateStorageUsageRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x10CheckEmailExists\x12\x17.dbservice.EmailRequest\x1a\x19.dbservice.ExistsResponse\"\x00\x12N\n" +
	"\x13CheckUsernameExists\x12\x1a.dbservice.UsernameRequest\x1a\x19.dbservice.ExistsResponse\"\x00\x122\n" +
	"\n" +
	"CreateFile\x12\x0f.dbservice.File\x1a\x11.dbservice.FileID\"\x00\x123\n" +
	"\vGetFileByID\x12\x11.dbservice.FileID\x1a\x0f.dbservice.File\"\x00\x12C\n" +
	"\rGetFileByPath\x12\x1f.dbservice.GetFileByPathRequest\x1a\x0f.dbservice.File\"\x00\x127\n" +
	"\n" +
	"UpdateFile\x12\x0f.dbservice.File\x1a\x16.google.protobuf.Empty\"\x00\x129\n" +
	"\n" +
	"DeleteFile\x12\x11.dbservice.FileID\x1a\x16.google.protobuf.Empty\"\x00\x12=\n" +
	"\x0eSoftDeleteFile\x12\x11.dbservice.FileID\x1a\x16.google.protobuf.Empty\"\x00\x12:\n" +
	"\vRestoreFile\x12\x11.dbservice.FileID\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\tListFiles\x12\x1b.dbservice.ListFilesRequest\x1a\x1c.dbservice.ListFilesResponse\"\x00\x12X\n" +
	"\x11ListFilesByParent\x12#.dbservice.ListFilesByParentRequest\x1a\x1c.dbservice.ListFilesResponse\"\x00\x12V\n" +
	"\x10ListStarredFiles\x12\".dbservice.ListStarredFilesRequest\x1a\x1c.dbservice.ListFilesResponse\"\x00\x12V\n" +
	"\x10ListTrashedFiles\x12\".dbservice.ListTrashedFilesRequest\x1a\x1c.dbservice.ListFilesResponse\"\x00\x12L\n" +
	"\vSearchFiles\x12\x1d.dbservice.SearchFilesRequest\x1a\x1c.dbservice.ListFilesResponse\"\x00\x12?\n" +
	"\vGetFileSize\x12\x11.dbservice.FileID\x1a\x1b.dbservice.FileSizeResponse\"\x00\x12L\n" +
	"\x0eUpdateFileSize\x12 .dbservice.UpdateFileSizeRequest\x1a\x16.google.protobuf.Empty\"\x00\x12?\n" +
	"\x10UpdateLastViewed\x12\x11.dbservice.FileID\x1a\x16.google.protobuf.Empty\"\x00\x12L\n" +
	"\vGetFileTree\x12\x1d.dbservice.GetFileTreeRequest\x1a\x1c.dbservice.ListFilesResponse\"\x00\x12B\n" +
	"\x0eCreateRevision\x12\x17.dbservice.FileRevision\x1a\x15.dbservice.RevisionID\"\x00\x12E\n" +
	"\fGetRevisions\x12\x11.dbservice.FileID\x1a .dbservice.ListRevisionsResponse\"\x00\x12G\n" +
	"\vGetRevision\x12\x1d.dbservice.GetRevisionRequest\x1a\x17.dbservice.FileRevision\"\x00\x12A\n" +
	"\x0eDeleteRevision\x12\x15.dbservice.RevisionID\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x10CreatePermission\x12\x19.dbservice.FilePermission\x1a\x17.dbservice.PermissionID\"\x00\x12I\n" +
	"\x0eGetPermissions\x12\x11.dbservice.FileID\x1a\".dbservice.ListPermissionsResponse\"\x00\x12G\n" +
	"\x10UpdatePermission\x12\x19.dbservice.FilePermission\x1a\x16.google.protobuf.Empty\"\x00\x12E\n" +
	"\x10DeletePermission\x12\x17.dbservice.PermissionID\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\x0fCheckPermission\x12!.dbservice.CheckPermissionRequest\x1a\x1d.dbservice.PermissionResponse\"\x00\x12T\n" +
	"\x12UpdateFileMetadata\x12$.dbservice.UpdateFileMetadataRequest\x1a\x16.google.protobuf.Empty\"\x00\x12G\n" +
	"\x0fGetFileMetadata\x12\x11.dbservice.FileID\x1a\x1f.dbservice.FileMetadataResponse\"\x00\x127\n" +
	"\bStarFile\x12\x11.dbservice.FileID\x1a\x16.google.protobuf.Empty\"\x00\x129\n" +
	"\n" +
	"UnstarFile\x12\x11.dbservice.FileID\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\bMoveFile\x12\x1a.dbservice.MoveFileRequest\x1a\x16.google.protobuf.Empty\"\x00\x129\n" +
	"\bCopyFile\x12\x1a.dbservice.CopyFileRequest\x1a\x0f.dbservice.File\"\x00\x12D\n" +
	"\n" +
	"RenameFile\x12\x1c.dbservice.RenameFileRequest\x1a\x16.google.protobuf.Empty\"\x00\x12H\n" +
	"\x13VerifyFileIntegrity\x12\x11.dbservice.FileID\x1a\x1c.dbservice.IntegrityResponse\"\x00\x12K\n" +
	"\x16CalculateFileChecksums\x12\x11.dbservice.FileID\x1a\x1c.dbservice.ChecksumsResponse\"\x00B7Z5homecloud-auth-service/internal/transport/grpc/protosb\x06proto3"

var (
	file_db_service_proto_rawDescOnce sync.Once
	file_db_service_proto_rawDescData []byte
)

func file_db_service_proto_rawDescGZIP() []byte {
	file_db_service_proto_rawDescOnce.Do(func() {
		file_db_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_db_service_proto_rawDesc), len(file_db_service_proto_rawDesc)))
	})
	return file_db_service_proto_rawDescData
}

var file_db_service_proto_msgTypes = make([]protoimpl.MessageInfo, 40)
var file_db_service_proto_goTypes = []any{
	(*User)(nil),                             // 0: dbservice.User
	(*UserID)(nil),                           // 1: dbservice.UserID
	(*EmailRequest)(nil),                     // 2: dbservice.EmailRequest
	(*UsernameRequest)(nil),                  // 3: dbservice.UsernameRequest
	(*UpdatePasswordRequest)(nil),            // 4: dbservice.UpdatePasswordRequest
	(*UpdateUsernameRequest)(nil),            // 5: dbservice.UpdateUsernameRequest
	(*UpdateEmailVerificationRequest)(nil),   // 6: dbservice.UpdateEmailVerificationRequest
	(*UpdateFailedLoginAttemptsRequest)(nil), // 7: dbservice.UpdateFailedLoginAttemptsRequest
	(*UpdateLockedUntilRequest)(nil),         // 8: dbservice.UpdateLockedUntilRequest
	(*UpdateStorageUsageRequest)(nil),        // 9: dbservice.UpdateStorageUsageRequest
	(*ExistsResponse)(nil),                   // 10: dbservice.ExistsResponse
	(*File)(nil),                             // 11: dbservice.File
	(*FileID)(nil),                           // 12: dbservice.FileID
	(*GetFileByPathRequest)(nil),             // 13: dbservice.GetFileByPathRequest
	(*ListFilesRequest)(nil),                 // 14: dbservice.ListFilesRequest
	(*ListFilesResponse)(nil),                // 15: dbservice.ListFilesResponse
	(*ListFilesByParentRequest)(nil),         // 16: dbservice.ListFilesByParentRequest
	(*ListStarredFilesRequest)(nil),          // 17: dbservice.ListStarredFilesRequest
	(*ListTrashedFilesRequest)(nil),          // 18: dbservice.ListTrashedFilesRequest
	(*SearchFilesRequest)(nil),               // 19: dbservice.SearchFilesRequest
	(*FileSizeResponse)(nil),                 // 20: dbservice.FileSizeResponse
	(*UpdateFileSizeRequest)(nil),            // 21: dbservice.UpdateFileSizeRequest
	(*GetFileTreeRequest)(nil),               // 22: dbservice.GetFileTreeRequest
	(*FileRevision)(nil),                     // 23: dbservice.FileRevision
	(*RevisionID)(nil),                       // 24: dbservice.RevisionID
	(*ListRevisionsResponse)(nil),            // 25: dbservice.ListRevisionsResponse
	(*GetRevisionRequest)(nil),               // 26: dbservice.GetRevisionRequest
	(*FilePermission)(nil),                   // 27: dbservice.FilePermission
	(*PermissionID)(nil),                     // 28: dbservice.PermissionID
	(*ListPermissionsResponse)(nil),          // 29: dbservice.ListPermissionsResponse
	(*CheckPermissionRequest)(nil),           // 30: dbservice.CheckPermissionRequest
	(*PermissionResponse)(nil),               // 31: dbservice.PermissionResponse
	(*UpdateFileMetadataRequest)(nil),        // 32: dbservice.UpdateFileMetadataRequest
	(*FileMetadataResponse)(nil),             // 33: dbservice.FileMetadataResponse
	(*MoveFileRequest)(nil),                  // 34: dbservice.MoveFileRequest
	(*CopyFileRequest)(nil),                  // 35: dbservice.CopyFileRequest
	(*RenameFileRequest)(nil),                // 36: dbservice.RenameFileRequest
	(*IntegrityResponse)(nil),                // 37: dbservice.IntegrityResponse
	(*ChecksumsResponse)(nil),                // 38: dbservice.ChecksumsResponse
	nil,                                      // 39: dbservice.ChecksumsResponse.ChecksumsEntry
	(*timestamppb.Timestamp)(nil),            // 40: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 41: google.protobuf.Empty
}
var file_db_service_proto_depIdxs = []int32{
	40, // 0: dbservice.User.created_at:type_name -> google.protobuf.Timestamp
	40, // 1: dbservice.User.updated_at:type_name -> google.protobuf.Timestamp
	40, // 2: dbservice.User.locked_until:type_name -> google.protobuf.Timestamp
	40, // 3: dbservice.User.last_login:type_name -> google.protobuf.Timestamp
	40, // 4: dbservice.UpdateLockedUntilRequest.locked_until:type_name -> google.protobuf.Timestamp
	40, // 5: dbservice.File.trashed_at:type_name -> google.protobuf.Timestamp
	40, // 6: dbservice.File.created_at:type_name -> google.protobuf.Timestamp
	40, // 7: dbservice.File.updated_at:type_name -> google.protobuf.Timestamp
	40, // 8: dbservice.File.last_viewed_at:type_name -> google.protobuf.Timestamp
	11, // 9: dbservice.ListFilesResponse.files:type_name -> dbservice.File
	40, // 10: dbservice.FileRevision.created_at:type_name -> google.protobuf.Timestamp
	23, // 11: dbservice.ListRevisionsResponse.revisions:type_name -> dbservice.FileRevision
	40, // 12: dbservice.FilePermission.created_at:type_name -> google.protobuf.Timestamp
	27, // 13: dbservice.ListPermissionsResponse.permissions:type_name -> dbservice.FilePermission
	39, // 14: dbservice.ChecksumsResponse.checksums:type_name -> dbservice.ChecksumsResponse.ChecksumsEntry
	0,  // 15: dbservice.DBService.CreateUser:input_type -> dbservice.User
	1,  // 16: dbservice.DBService.GetUserByID:input_type -> dbservice.UserID
	2,  // 17: dbservice.DBService.GetUserByEmail:input_type -> dbservice.EmailRequest
	0,  // 18: dbservice.DBService.UpdateUser:input_type -> dbservice.User
	4,  // 19: dbservice.DBService.UpdatePassword:input_type -> dbservice.UpdatePasswordRequest
	5,  // 20: dbservice.DBService.UpdateUsername:input_type -> dbservice.UpdateUsernameRequest
	6,  // 21: dbservice.DBService.UpdateEmailVerification:input_type -> dbservice.UpdateEmailVerificationRequest
	1,  // 22: dbservice.DBService.UpdateLastLogin:input_type -> dbservice.UserID
	7,  // 23: dbservice.DBService.UpdateFailedLoginAttempts:input_type -> dbservice.UpdateFailedLoginAttemptsRequest
	8,  // 24: dbservice.DBService.UpdateLockedUntil:input_type -> dbservice.UpdateLockedUntilRequest
	9,  // 25: dbservice.DBService.UpdateStorageUsage:input_type -> dbservice.UpdateStorageUsageRequest
	2,  // 26: dbservice.DBService.CheckEmailExists:input_type -> dbservice.EmailRequest
	3,  // 27: dbservice.DBService.CheckUsernameExists:input_type -> dbservice.UsernameRequest
	11, // 28: dbservice.DBService.CreateFile:input_type -> dbservice.File
	12, // 29: dbservice.DBService.GetFileByID:input_type -> dbservice.FileID
	13, // 30: dbservice.DBService.GetFileByPath:input_type -> dbservice.GetFileByPathRequest
	11, // 31: dbservice.DBService.UpdateFile:input_type -> dbservice.File
	12, // 32: dbservice.DBService.DeleteFile:input_type -> dbservice.FileID
	12, // 33: dbservice.DBService.SoftDeleteFile:input_type -> dbservice.FileID
	12, // 34: dbservice.DBService.RestoreFile:input_type -> dbservice.FileID
	14, // 35: dbservice.DBService.ListFiles:input_type -> dbservice.ListFilesRequest
	16, // 36: dbservice.DBService.ListFilesByParent:input_type -> dbservice.ListFilesByParentRequest
	17, // 37: dbservice.DBService.ListStarredFiles:input_type -> dbservice.ListStarredFilesRequest
	18, // 38: dbservice.DBService.ListTrashedFiles:input_type -> dbservice.ListTrashedFilesRequest
	19, // 39: dbservice.DBService.SearchFiles:input_type -> dbservice.SearchFilesRequest
	12, // 40: dbservice.DBService.GetFileSize:input_type -> dbservice.FileID
	21, // 41: dbservice.DBService.UpdateFileSize:input_type -> dbservice.UpdateFileSizeRequest
	12, // 42: dbservice.DBService.UpdateLastViewed:input_type -> dbservice.FileID
	22, // 43: dbservice.DBService.GetFileTree:input_type -> dbservice.GetFileTreeRequest
	23, // 44: dbservice.DBService.CreateRevision:input_type -> dbservice.FileRevision
	12, // 45: dbservice.DBService.GetRevisions:input_type -> dbservice.FileID
	26, // 46: dbservice.DBService.GetRevision:input_type -> dbservice.GetRevisionRequest
	24, // 47: dbservice.DBService.DeleteRevision:input_type -> dbservice.RevisionID
	27, // 48: dbservice.DBService.CreatePermission:input_type -> dbservice.FilePermission
	12, // 49: dbservice.DBService.GetPermissions:input_type -> dbservice.FileID
	27, // 50: dbservice.DBService.UpdatePermission:input_type -> dbservice.FilePermission
	28, // 51: dbservice.DBService.DeletePermission:input_type -> dbservice.PermissionID
	30, // 52: dbservice.DBService.CheckPermission:input_type -> dbservice.CheckPermissionRequest
	32, // 53: dbservice.DBService.UpdateFileMetadata:input_type -> dbservice.UpdateFileMetadataRequest
	12, // 54: dbservice.DBService.GetFileMetadata:input_type -> dbservice.FileID
	12, // 55: dbservice.DBService.StarFile:input_type -> dbservice.FileID
	12, // 56: dbservice.DBService.UnstarFile:input_type -> dbservice.FileID
	34, // 57: dbservice.DBService.MoveFile:input_type -> dbservice.MoveFileRequest
	35, // 58: dbservice.DBService.CopyFile:input_type -> dbservice.CopyFileRequest
	36, // 59: dbservice.DBService.RenameFile:input_type -> dbservice.RenameFileRequest
	12, // 60: dbservice.DBService.VerifyFileIntegrity:input_type -> dbservice.FileID
	12, // 61: dbservice.DBService.CalculateFileChecksums:input_type -> dbservice.FileID
	1,  // 62: dbservice.DBService.CreateUser:output_type -> dbservice.UserID
	0,  // 63: dbservice.DBService.GetUserByID:output_type -> dbservice.User
	0,  // 64: dbservice.DBService.GetUserByEmail:output_type -> dbservice.User
	41, // 65: dbservice.DBService.UpdateUser:output_type -> google.protobuf.Empty
	41, // 66: dbservice.DBService.UpdatePassword:output_type -> google.protobuf.Empty
	41, // 67: dbservice.DBService.UpdateUsername:output_type -> google.protobuf.Empty
	41, // 68: dbservice.DBService.UpdateEmailVerification:output_type -> google.protobuf.Empty
	41, // 69: dbservice.DBService.UpdateLastLogin:output_type -> google.protobuf.Empty
	41, // 70: dbservice.DBService.UpdateFailedLoginAttempts:output_type -> google.protobuf.Empty
	41, // 71: dbservice.DBService.UpdateLockedUntil:output_type -> google.protobuf.Empty
	41, // 72: dbservice.DBService.UpdateStorageUsage:output_type -> google.protobuf.Empty
	10, // 73: dbservice.DBService.CheckEmailExists:output_type -> dbservice.ExistsResponse
	10, // 74: dbservice.DBService.CheckUsernameExists:output_type -> dbservice.ExistsResponse
	12, // 75: dbservice.DBService.CreateFile:output_type -> dbservice.FileID
	11, // 76: dbservice.DBService.GetFileByID:output_type -> dbservice.File
	11, // 77: dbservice.DBService.GetFileByPath:output_type -> dbservice.File
	41, // 78: dbservice.DBService.UpdateFile:output_type -> google.protobuf.Empty
	41, // 79: dbservice.DBService.DeleteFile:output_type -> google.protobuf.Empty
	41, // 80: dbservice.DBService.SoftDeleteFile:output_type -> google.protobuf.Empty
	41, // 81: dbservice.DBService.RestoreFile:output_type -> google.protobuf.Empty
	15, // 82: dbservice.DBService.ListFiles:output_type -> dbservice.ListFilesResponse
	15, // 83: dbservice.DBService.ListFilesByParent:output_type -> dbservice.ListFilesResponse
	15, // 84: dbservice.DBService.ListStarredFiles:output_type -> dbservice.ListFilesResponse
	15, // 85: dbservice.DBService.ListTrashedFiles:output_type -> dbservice.ListFilesResponse
	15, // 86: dbservice.DBService.SearchFiles:output_type -> dbservice.ListFilesResponse
	20, // 87: dbservice.DBService.GetFileSize:output_type -> dbservice.FileSizeResponse
	41, // 88: dbservice.DBService.UpdateFileSize:output_type -> google.protobuf.Empty
	41, // 89: dbservice.DBService.UpdateLastViewed:output_type -> google.protobuf.Empty
	15, // 90: dbservice.DBService.GetFileTree:output_type -> dbservice.ListFilesResponse
	24, // 91: dbservice.DBService.CreateRevision:output_type -> dbservice.RevisionID
	25, // 92: dbservice.DBService.GetRevisions:output_type -> dbservice.ListRevisionsResponse
	23, // 93: dbservice.DBService.GetRevision:output_type -> dbservice.FileRevision
	41, // 94: dbservice.DBService.DeleteRevision:output_type -> google.protobuf.Empty
	28, // 95: dbservice.DBService.CreatePermission:output_type -> dbservice.PermissionID
	29, // 96: dbservice.DBService.GetPermissions:output_type -> dbservice.ListPermissionsResponse
	41, // 97: dbservice.DBService.UpdatePermission:output_type -> google.protobuf.Empty
	41, // 98: dbservice.DBService.DeletePermission:output_type -> google.protobuf.Empty
	31, // 99: dbservice.DBService.CheckPermission:output_type -> dbservice.PermissionResponse
	41, // 100: dbservice.DBService.UpdateFileMetadata:output_type -> google.protobuf.Empty
	33, // 101: dbservice.DBService.GetFileMetadata:output_type -> dbservice.FileMetadataResponse
	41, // 102: dbservice.DBService.StarFile:output_type -> google.protobuf.Empty
	41, // 103: dbservice.DBService.UnstarFile:output_type -> google.protobuf.Empty
	41, // 104: dbservice.DBService.MoveFile:output_type -> google.protobuf.Empty
	11, // 105: dbservice.DBService.CopyFile:output_type -> dbservice.File
	41, // 106: dbservice.DBService.RenameFile:output_type -> google.protobuf.Empty
	37, // 107: dbservice.DBService.VerifyFileIntegrity:output_type -> dbservice.IntegrityResponse
	38, // 108: dbservice.DBService.CalculateFileChecksums:output_type -> dbservice.ChecksumsResponse
	62, // [62:109] is the sub-list for method output_type
	15, // [15:62] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_db_service_proto_init() }
func file_db_service_proto_init() {
	if File_db_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_db_service_proto_rawDesc), len(file_db_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   40,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_db_service_proto_goTypes,
		DependencyIndexes: file_db_service_proto_depIdxs,
		MessageInfos:      file_db_service_proto_msgTypes,
	}.Build()
	File_db_service_proto = out.File
	file_db_service_proto_goTypes = nil
	file_db_service_proto_depIdxs = nil
}
